name: Deploy obo-kafka-manager to prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "obo-kafka-manager/prod/*.yaml"

jobs:
  deploy-prod:
    name: Deploy obo-kafka-manager to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ./obo-kafka-manager/prod/nais.yaml
          PRINT_PAYLOAD: true
