name: Deploy obo-kafka-manager to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "obo-kafka-manager/dev/*.yaml"

jobs:
  deploy-dev:
    name: Deploy obo-kafka-manager to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ./obo-kafka-manager/dev/nais.yaml
          PRINT_PAYLOAD: true
